name: CI Pipeline

on:
    pull_request:
        branches: [main, develop]
    push:
        branches: [main, develop]
    workflow_dispatch:
        
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0'

            - name: Restore Dependencies and Build Solution
              run: |
                dotnet restore GovConnect.sln
                dotnet build GovConnect.sln --configuration Release

            - name: Run Tests
              run: |
                dotnet test ./GovConnect.Application.IntegrationTests/GovConnect.Application.IntegrationTests.csproj --no-build --verbosity normal
                dotnet test ./GovConnect.Infrastructure.IntegrationTests/GovConnect.Infrastructure.IntegrationTests.csproj --no-build --verbosity normal