name: CI Pipeline

on:
    pull_request:
        branches: [main, develop]
        
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup .NET Application
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.*'

            - name: Restore Dependencies
              uses: dotnet restore

            - name: Build Solution
              uses: dotnet build --no-restore --configuration Release

            - name: Run Tests
              uses: dotnet test --no-build --configuration Release