name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET Application
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore Dependencies
      run: dotnet restore
      
    - name: Build Solution
      run: dotnet build --no-restore

  security-check:
    runs-on: ubuntu-latest
    needs: compile
    steps:
    - uses: actions/checkout@v4
    
    - name: Trivy Installation
      run: |
        sudo apt-get install wget gnupg
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update -y
        sudo apt-get install trivy -y

    - name: Trivy Scan
      run: trivy fs --format table -o fs-report.json .

      # Add Gitleaks Installation
      # And Gitleaks Code Scan here

  integration-test:
    runs-on: ubuntu-latest
    needs: security-check
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET Application
      with:
        dotnet-version: 8.0.x
        
    - name: Restore Dependencies
      run: dotnet restore
      
    - name: Build Solution
      run: dotnet build --no-restore
      
    - name: Run Integration Tests
      run: dotnet test --filter "Category=Integration"
